### ISSUE TITLE
Do I have to install this version of PyTorch==1.8?

### ISSUE THREAD

**Issue by BrotherHappy** [ModelTC/MQBench#121]
my cuda version is 11.1 .
i cant install the pytorch-gpu==1.8 that  support cuda11.1?
so i want to ask that if pytorch==1.9 is ok?

**Comment by Tracin** [comment]
Pytorch 1.9 1.10 but not 1.11 is ok.

**Comment by urbste** [comment]
1.10 is not working for ONNX_QNN:
```
  File "/home/zosurban/anaconda3/envs/lib/python3.9/site-packages/MQBench-0.0.6-py3.9.egg/mqbench/custom_quantizer/onnx_qnn_quantizer.py", line 60, in _qat_swap_modules
    del(all_mappings[torch.nn.modules.linear._LinearWithBias])
AttributeError: module 'torch.nn.modules.linear' has no attribute '_LinearWithBias'
```

If we replace onnx_qnn_quantizer.py line 60:
`del(all_mappings[torch.nn.modules.linear._LinearWithBias])`
with
`del(all_mappings[torch.nn.modules.linear.NonDynamicallyQuantizableLinear])`
it works.

**Comment by urbste** [comment]
But then I run into the next error:
```
  File "/home/zosurban/anaconda3/envs/lib/python3.9/site-packages/MQBench-0.0.6-py3.9.egg/mqbench/deploy/deploy_onnx_qnn.py", line 199, in search_and_replace_input
    for idx, _input_name in enumerate(next_node.input):
AttributeError: 'str' object has no attribute 'input'
```

**Comment by Tracin** [comment]
@PannenetsF 

> But then I run into the next error:
> 
> ```
>   File "/home/zosurban/anaconda3/envs/prismalearn/lib/python3.9/site-packages/MQBench-0.0.6-py3.9.egg/mqbench/deploy/deploy_onnx_qnn.py", line 199, in search_and_replace_input
>     for idx, _input_name in enumerate(next_node.input):
> AttributeError: 'str' object has no attribute 'input'
> ```

**Comment by PannenetsF** [comment]
@urbste Please provide the detailed reproduction code and steps so that I can solve the problem.

**Comment by urbste** [comment]
Cool thanks for taking a look at it. 
Tested with:
- pytorch 1.8.1+cu111
- onnx 1.12.0

[MinimalExample.zip](https://github.com/ModelTC/MQBench/files/9029450/MinimalExample.zip)

**Comment by PannenetsF** [comment]
#126 Fix this issue, and we will add unet to our unittest. Thanks for your feedback!

**Comment by urbste** [comment]
Great it works! Just a remark about the Unet that I used. I had to comment the automatic padding calculations in the UP sampling block: So this network only works for specific input sizes. (I think divisible by 8). Otherwise the PyTorch tracing does not work.

```
def forward(self, x1, x2):
        x1 = self.up(x1)
        #diffY = x2.size()[2] - x1.size()[2]
        #diffX = x2.size()[3] - x1.size()[3]
        #print(diffY, diffX)
        #x1 = F.pad(x1, [diffX // 2, diffX - diffX // 2, diffY // 2, diffY - diffY // 2])
        x = torch.cat([x2, x1], dim=1)

        return self.conv(x)
```

**Comment by PannenetsF** [comment]
&nbsp;You can open a new issue so we can talk about this problem.



---Original---
From: "Steffen ***@***.***&gt;
Date: Mon, Jul 4, 2022 15:01 PM
To: ***@***.***&gt;;
Cc: "Yunqian ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [ModelTC/MQBench] Do I have to install this version ofPyTorch==1.8? (Issue #121)




 
Great it works! Just a remark about the Unet that I used. I had to comment the automatic padding calculations in the UP sampling block: So this network only works for specific input sizes. (I think divisible by 8). Otherwise the PyTorch tracing does not work.
 def forward(self, x1, x2):         x1 = self.up(x1)         #diffY = x2.size()[2] - x1.size()[2]         #diffX = x2.size()[3] - x1.size()[3]         #print(diffY, diffX)         #x1 = F.pad(x1, [diffX // 2, diffX - diffX // 2, diffY // 2, diffY - diffY // 2])         x = torch.cat([x2, x1], dim=1)         return self.conv(x)
